#### Задание 1

In [14]:
import numpy as np
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])
print(a)
mean_a = a.mean(axis=1)
print("Средние значения строк: {}".format(mean_a))



[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
Средние значения строк: [2.  8.4]


#### Задание 2

In [17]:
a_centered = a - 2
print(a_centered)

[[-1  0  1  1 -1]
 [ 4  6  9  8  5]]
