### Задание 1
Загрузите "Boston House Prices dataset" из встроенных наборов данных библиотеки sklearn. Создайте датафреймы X и y из этих данных...

In [28]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.metrics import r2_score

import warnings
warnings.filterwarnings('ignore')

In [29]:
boston = load_boston()
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [30]:
print(boston['data'])
boston['data'].shape

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


(506, 13)

In [31]:
type(boston) 

sklearn.utils.Bunch

In [32]:
boston['DESCR']

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [35]:
data = boston["data"]
feature_names = boston["feature_names"]
X = pd.DataFrame(data, columns = feature_names)
y = pd.DataFrame(data, columns = feature_names)

In [53]:
boston["target"]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [54]:
target = boston["target"]
y = pd.DataFrame(target, columns = ["price"])
y

price
0     24.0
1     21.6
2     34.7
3     33.4
4     36.2
..     ...
501   22.4
502   20.6
503   23.9
504   22.0
505   11.9

[506 rows x 1 columns]

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [46]:
X_test

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
173  0.09178   0.0   4.05   0.0  0.510  6.416  84.1  2.6463   5.0  296.0   
274  0.05644  40.0   6.41   1.0  0.447  6.758  32.9  4.0776   4.0  254.0   
491  0.10574   0.0  27.74   0.0  0.609  5.983  98.8  1.8681   4.0  711.0   
72   0.09164   0.0  10.81   0.0  0.413  6.065   7.8  5.2873   4.0  305.0   
452  5.09017   0.0  18.10   0.0  0.713  6.297  91.8  2.3682  24.0  666.0   
..       ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
110  0.10793   0.0   8.56   0.0  0.520  6.195  54.4  2.7778   5.0  384.0   
321  0.18159   0.0   7.38   0.0  0.493  6.376  54.3  4.5404   5.0  287.0   
265  0.76162  20.0   3.97   0.0  0.647  5.560  62.8  1.9865   5.0  264.0   
29   1.00245   0.0   8.14   0.0  0.538  6.674  87.3  4.2390   4.0  307.0   
262  0.52014  20.0   3.97   0.0  0.647  8.398  91.5  2.2885   5.0  264.0   

     PTRATIO       B  LSTAT  
173     16.6  395.50   9.04  
274     17.6  396.90   3.53  
491     20.1  390.11  18.07  
72      19.2  390.91   5.52  
452     20.2  385.09  17.27  
..       ...     ...    ...  
110     20.9  393.49  13.00  
321     19.6  396.90   6.87  
265     13.0  392.40  10.45  
29      21.0  380.23  11.98  
262     13.0  386.86   5.91  

[167 rows x 13 columns]

In [47]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [48]:
y_pred = lr.predict(X_test)
y_pred.shape

(167, 1)

In [50]:
check_test = pd.DataFrame({
    "y_test": y_test["price"],
    "y_pred": y_pred.flatten(),
})

check_test.head(10)

y_test     y_pred
173    23.6  28.534695
274    32.4  36.618701
491    13.6  15.637511
72     22.8  25.501450
452    16.1  18.709673
76     20.0  23.164716
316    17.8  17.310110
140    14.0  14.077364
471    19.6  23.010644
500    16.8  20.542235

In [55]:
check_test["error"] = check_test["y_pred"] - check_test["y_test"]
check_test.head()

y_test     y_pred     error
173    23.6  28.534695  4.934695
274    32.4  36.618701  4.218701
491    13.6  15.637511  2.037511
72     22.8  25.501450  2.701450
452    16.1  18.709673  2.609673

In [60]:
R2 = r2_score(check_test["y_pred"], check_test["y_test"])
R2

0.6709558976744436

### Задание 2

In [73]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators = 1000, max_depth = 12, random_state = 42)
model.fit(X_train, y_train.values[:, 0])

RandomForestRegressor(max_depth=12, n_estimators=1000, random_state=42)

In [74]:
y_pred = model.predict(X_test)
y_pred.shape

(167,)

In [75]:
check_test = pd.DataFrame({
    "y_test": y_test["price"],
    "y_pred": y_pred.flatten(),
})
check_test.head(10)

y_test     y_pred
173    23.6  22.633172
274    32.4  31.401489
491    13.6  16.604033
72     22.8  23.680828
452    16.1  17.092412
76     20.0  21.596315
316    17.8  19.973690
140    14.0  14.881983
471    19.6  21.315430
500    16.8  21.190421

In [76]:
check_test["error"] = check_test["y_pred"] - check_test["y_test"]
check_test.head()

y_test     y_pred     error
173    23.6  22.633172 -0.966828
274    32.4  31.401489 -0.998511
491    13.6  16.604033  3.004033
72     22.8  23.680828  0.880828
452    16.1  17.092412  0.992412

In [77]:
R2 = r2_score(check_test["y_pred"], check_test["y_test"])
R2

0.8313119473735879